[server]
port=9123

[theme]
base="light"
primaryColor = "#f63366"
backgroundColor = "#fafeff"
textColor = "#00172B"
font = "sans serif"
secondaryBackgroundColor = "#d3eaf2"

[runner]
fastReruns = true