[server]
port=9123

[theme]
base="light"
primaryColor = "#be2596"
backgroundColor = "#fafeff"
textColor = "#00172B"
font = "monospace"
secondaryBackgroundColor = "#d3eaf2"

[runner]
fastReruns = true
magicEnabled = false